In [45]:
import numpy as np
import numpy.linalg as la
mu = np.array([0,0]).reshape(2,1)
su = np.array([[1,0.9],[0.9,1]])
A = np.array([1,1]).reshape(2,1)
B = np.array([1,-1]).reshape(2,1)
#马氏距离
mahalanobis = np.sqrt((A-B).T@la.inv(su)@(A-B))
print('马氏距离结果为：',mahalanobis[0])
#欧氏距离
sum = 0
for i in range(len(A)):
    sum = sum + (A[i]-B[i])**2
euclidean = np.sqrt(sum)
print('欧氏距离结果为：',euclidean)
#曼哈顿距离
total = 0
for i in range(len(A)):
    total = total + np.abs(A[i]-B[i])
manhattan = total
print('曼哈顿距离结果为：',manhattan)
#切比雪夫距离
maxmanhattan = []
for i in range(len(A)):
    d = np.abs(A[i]-B[i])
    maxmanhattan.append(d)
chebyshev = np.max(maxmanhattan)
print('切比雪夫距离结果为：',chebyshev)

马氏距离结果为： [4.58831468]
欧氏距离结果为： [2.]
曼哈顿距离结果为： [2]
切比雪夫距离结果为： 2


In [44]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
x1 = np.array([[3,2],[2,4],[4,7]])
x2 = np.array([[6,9],[5,7],[4,8]])
m1 = np.mean(x1,axis=0)
m2 = np.mean(x2,axis=0)
print(m1,'\n\n',m2,'\n')
v1 = np.cov(x1.T)
v2 = np.cov(x2.T)
print(v1,'\n\n',v2,'\n')
x0 = np.r_[x1,x2]
v = np.cov(x0.T)
y0 = np.hstack([np.ones(3),2*np.ones(3)])
#判别
knn = KNeighborsClassifier(2,metric='mahalanobis',metric_params={'V':v})
knn.fit(x0,y0)

#预测
x = np.array([[2,7]])
pre = knn.predict(x)
print('马氏距离分类结果：',pre)
print('马氏距离已知样本的误判率为：',1-knn.score(x0,y0))

[3.         4.33333333] 

 [5. 8.] 

[[1.         1.5       ]
 [1.5        6.33333333]] 

 [[1.  0.5]
 [0.5 1. ]] 

马氏距离分类结果： [1.]
马氏距离已知样本的误判率为： 0.16666666666666663


In [73]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import cross_val_score
a = np.loadtxt('11_14.txt')
x0 = a[0:-3,1:]
y0 = np.hstack([np.ones(3),2*np.ones(5)])
x = a[-3:,1:]
v = np.cov(x0.T)
knn = KNeighborsClassifier(2,metric='mahalanobis',metric_params={'V':v})
knn.fit(x0,y0)
pre = knn.predict(x)
print('马氏距离分类结果：',pre)
print('马氏距离已知样本的误判率为：',1-knn.score(x0,y0))
print('交叉误判率为：',cross_val_score(knn,x0,y0,cv=2))
print('\n')
knn2 = KNeighborsClassifier(2)
knn2.fit(x0,y0)
pre2 = knn2.predict(x)
print('欧氏距离分类结果：',pre2)
print('欧氏距离已知样本的误判率为：',1-knn2.score(x0,y0))
print('交叉误判率为：',cross_val_score(knn2,x0,y0,cv=2))
print('\n')
clf = LDA()
clf.fit(x0,y0)
print('Fisher准则判别结果为：',clf.predict(x))
print('Fisher准则已知样本的误判率为：',1-clf.score(x0,y0))
model = LDA()
print('交叉误判率为：',cross_val_score(model,x0,y0,cv=2))
print('\n')
clf2 = GaussianNB()
clf2.fit(x0,y0)
print('贝叶斯判别法结果为：',clf.predict(x))
print('贝叶斯判别法已知样本的误判率为：',1-clf.score(x0,y0))
model1 = GaussianNB()
print('交叉误判率为：',cross_val_score(model1,x0,y0,cv=2))

马氏距离分类结果： [1. 1. 1.]
马氏距离已知样本的误判率为： 0.125
交叉误判率为： [0.5  0.25]


欧氏距离分类结果： [1. 2. 1.]
欧氏距离已知样本的误判率为： 0.125
交叉误判率为： [1.   0.75]


Fisher准则判别结果为： [1. 1. 1.]
Fisher准则已知样本的误判率为： 0.0
交叉误判率为： [0.25 0.5 ]


贝叶斯判别法结果为： [1. 1. 1.]
贝叶斯判别法已知样本的误判率为： 0.0
交叉误判率为： [0.5  0.75]


d:\venv\suanfa\suanfa\lib\site-packages\sklearn\metrics\pairwise.py:1458: FutureWarning: from version 0.25, pairwise_distances for metric='mahalanobis' will require VI to be specified if Y is passed.
  "specified if Y is passed.", FutureWarning)
d:\venv\suanfa\suanfa\lib\site-packages\sklearn\metrics\pairwise.py:1458: FutureWarning: from version 0.25, pairwise_distances for metric='mahalanobis' will require VI to be specified if Y is passed.
  "specified if Y is passed.", FutureWarning)


In [2]:
import numpy as np
from sklearn.decomposition import PCA
a = np.loadtxt('11_15.txt')
md = PCA().fit(a) #构造并训练模型
print('特征值：',md.explained_variance_)
print('各主成分的贡献率：',md.explained_variance_ratio_)
print('奇异值为：',md.singular_values_)
print('各主成分系数为：\n',md.components_)

特征值： [3.01203072e+06 1.90907586e+06 3.00594423e+05 8.23494665e+04
 4.08692087e+04 5.32345367e+03 4.22321325e+00 4.17446651e-01]
各主成分的贡献率： [5.62970324e-01 3.56820084e-01 5.61832713e-02 1.53917108e-02
 7.63875065e-03 9.94991987e-04 7.89349098e-07 7.80237979e-08]
奇异值为： [9.34606286e+03 7.44064513e+03 2.95249695e+03 1.54535903e+03
 1.08867215e+03 3.92912403e+02 1.10667603e+01 3.47936099e+00]
各主成分系数为：
 [[ 7.60308252e-01  3.05917212e-01  2.19892586e-01  4.44404555e-01
   9.64855551e-02 -3.37571100e-04 -5.21272311e-04  2.70532837e-01]
 [-4.67925653e-01  3.59031519e-01 -6.11510952e-02  7.46059501e-01
  -2.43860248e-01  3.38129975e-05 -4.98856066e-04 -1.79804462e-01]
 [-1.80068548e-01  8.36910812e-01 -6.32184975e-02 -4.23685553e-01
   9.62320168e-02 -3.11949638e-04 -4.96255208e-04  2.72742808e-01]
 [-2.52267675e-01 -1.43543201e-01 -1.91050507e-01  2.48337703e-01
   8.46978752e-01 -3.35658754e-04 -7.88315269e-05  3.16561736e-01]
 [ 1.52342982e-01  2.32312421e-01  1.18623605e-01 -6.38853332e-02
  

In [7]:
import numpy as np
from scipy.stats import zscore
a = np.loadtxt('11_15.txt')
print('相关系数矩阵为：\n',np.corrcoef(a.T))
# b = np.delete(a,0,axis=1) #删除第一列数据
c = zscore(a) #标准化
r = np.corrcoef(c.T)  #标准化相关系数矩阵
d,e = np.linalg.eig(r)  #特征值和特征向量
rate = d/d.sum()  #计算各主成分的贡献率
print('特征值为：',d)
print('特征向量为：\n',e)
print('各主成分的贡献率为：',rate)
k = 1
F = e[:,:k]
score_mat = c.dot(F)
score1 = score_mat.dot(rate[0:k])
score2=-score1
print('各评价对象的得分为：',score2)
index = score1.argsort()+1
print('从高到低各个城市的编号排序为：',index)

相关系数矩阵为：
 [[ 1.          0.2667824   0.95056797  0.19077246  0.61709973 -0.27249317
  -0.26377155  0.87377354]
 [ 0.2667824   1.          0.42613689  0.71813394 -0.15101233 -0.23513868
  -0.59272738  0.36309899]
 [ 0.95056797  0.42613689  1.          0.39962743  0.43062333 -0.28048675
  -0.35905241  0.79186092]
 [ 0.19077246  0.71813394  0.39962743  1.         -0.35558521 -0.13495849
  -0.53915927  0.10438206]
 [ 0.61709973 -0.15101233  0.43062333 -0.35558521  1.         -0.25317541
   0.02172214  0.65857654]
 [-0.27249317 -0.23513868 -0.28048675 -0.13495849 -0.25317541  1.
   0.762838   -0.1252172 ]
 [-0.26377155 -0.59272738 -0.35905241 -0.53915927  0.02172214  0.762838
   1.         -0.19207416]
 [ 0.87377354  0.36309899  0.79186092  0.10438206  0.65857654 -0.1252172
  -0.19207416  1.        ]]
特征值为： [3.7551733  2.19662819 1.21491322 0.40243454 0.01465388 0.21279581
 0.06545111 0.13794995]
特征向量为：
 [[-0.4566508  -0.25878505  0.10972412 -0.3203807  -0.76017321 -0.14889612
   0.09418791

In [11]:
import numpy as np
R = np.array([[1,0.8,0.37,0.78,0.26,0.38],
              [0.8,1,0.32,0.65,0.18,0.33],
              [0.37,0.32,1,0.36,0.71,0.62],
              [0.78,0.65,0.36,1,0.18,0.39],
              [0.26,0.18,0.71,0.18,1,0.69],
              [0.38,0.33,0.62,0.39,0.69,1]])
d,e = np.linalg.eig(R)
rate = d/d.sum()
print('特征值为：',d)
print('特征向量为：\n',e)
print('各主成分的贡献率为：',rate)

特征值为： [3.35097027 1.51599708 0.14462131 0.24757787 0.3542329  0.38660056]
特征向量为：
 [[ 0.44696175  0.38113174  0.72002027  0.35171682 -0.08202847 -0.07811029]
 [ 0.40773446  0.40522194 -0.41138775 -0.31042318 -0.57017021 -0.28080469]
 [ 0.40542498 -0.38000468  0.1482083  -0.43166168  0.42043727 -0.5533191 ]
 [ 0.41835961  0.36743384 -0.41774048  0.14172746  0.6312124   0.3113595 ]
 [ 0.35549178 -0.53463092 -0.29884206  0.66253644 -0.20810023 -0.12739133]
 [ 0.41013317 -0.35396661  0.16294645 -0.36682381 -0.2228788   0.70406832]]
各主成分的贡献率为： [0.55849505 0.25266618 0.02410355 0.04126298 0.05903882 0.06443343]


In [2]:
import numpy as np
r = np.array([[1,0.8,0.37,0.78,0.26,0.38],
              [0.8,1,0.32,0.65,0.18,0.33],
              [0.37,0.32,1,0.36,0.71,0.62],
              [0.78,0.65,0.36,1,0.18,0.39],
              [0.26,0.18,0.71,0.18,1,0.69],
              [0.38,0.33,0.62,0.39,0.69,1]])
[val,vec] = np.linalg.eig(r)  #相关矩阵的特征值和特征向量
A1 = np.tile(np.sqrt(val),(6,1))*vec
A2 = vec*np.sqrt(val)
print('val:',val,'\n------\n',A1,'\n------\n',A2)
num = int(input('请输入选择公共因子的个数：'))
A = A1[:,:num]
Ac = np.sum(A**2,axis=0)
Ar = np.sum(A**2,axis=1)
print('对x的贡献为：',Ac)
print('共同度为：',Ar)

val: [3.35097027 1.51599708 0.14462131 0.24757787 0.3542329  0.38660056] 
------
 [[ 0.81819278  0.46927163  0.27381729  0.17500443 -0.04882127 -0.0485668 ]
 [ 0.74638467  0.4989329  -0.1564471  -0.15445788 -0.33935087 -0.17459652]
 [ 0.742157   -0.46788393  0.05636229 -0.21478275  0.25023362 -0.34403838]
 [ 0.7658347   0.45240598 -0.15886298  0.07051961  0.37568164  0.19359465]
 [ 0.65075101 -0.65826878 -0.11364697  0.32965956 -0.12385599 -0.07920838]
 [ 0.75077566 -0.43582434  0.06196708 -0.18252125 -0.13265182  0.43777005]] 
------
 [[ 0.81819278  0.46927163  0.27381729  0.17500443 -0.04882127 -0.0485668 ]
 [ 0.74638467  0.4989329  -0.1564471  -0.15445788 -0.33935087 -0.17459652]
 [ 0.742157   -0.46788393  0.05636229 -0.21478275  0.25023362 -0.34403838]
 [ 0.7658347   0.45240598 -0.15886298  0.07051961  0.37568164  0.19359465]
 [ 0.65075101 -0.65826878 -0.11364697  0.32965956 -0.12385599 -0.07920838]
 [ 0.75077566 -0.43582434  0.06196708 -0.18252125 -0.13265182  0.43777005]]
对x的贡献为：