In [1]:
import cvxpy as cp
import numpy as np
c = np.array([150,210,60,80,180])
a = np.array([[210,300,100,130,260],[1,1,1,0,0],[0,0,1,1,0],[-1,0,0,0,1]])
b = np.array([600,1,1,0])
x = cp.Variable(5,integer=True)
obj = cp.Maximize(c@x)
con = [0<=x,x<=1,
       a@x<=b]
prob = cp.Problem(obj,con)
prob.solve(solver = 'GLPK_MI',verbose = True)
print('最优解：',prob.value)
print('最优值：\n',x.value)

最优解： 410.0
最优值：
 [1. 0. 0. 1. 1.]


In [2]:
import cvxpy as cp
import numpy as np
c = np.array([3,5,2,4,2,3])
a = np.array([8,13,6,9,5,7])
b = np.array([24])
x = cp.Variable(6,integer=True)
obj = cp.Maximize(c@x)
con = [0<=x,x<=1,
       a@x<=b]
prob = cp.Problem(obj,con)
prob.solve(solver = 'GLPK_MI',verbose = True)
print('最优解：',prob.value)
print('最优值：\n',x.value)

最优解： 10.0
最优值：
 [1. 0. 0. 1. 0. 1.]


In [3]:
import numpy as np
import cvxpy as cp
c1 = np.array([200,200,200])
c2 = np.array([5800,5400,50])
a = np.array([[-1,0,0],[-1,-1,0]])
b = np.array([-40,-100])
c = np.array([1,1,1])
e = np.array([180])
x = cp.Variable(3,integer=True)
obj = cp.Minimize(c1@x**2+c2@x)
con = [0<=x,x<=100,a@x<=b,c@x==e]
prob = cp.Problem(obj,con)
prob.solve()
print('最优值为：',prob.value-560000)
print('最优解为：\n',x.value)
print('第一季度生产{}台，第二季度生产{}台，第三季度生产{}台'
      .format(int(x.value[0]),int(x.value[1]),int(x.value[2])))

最优值为： 2249250.0
最优解为：
 [55. 56. 69.]
第一季度生产55台，第二季度生产56台，第三季度生产69台


In [29]:
import numpy as np
from scipy.optimize import minimize
c = np.array([[1,4,5],[4,2,6],[5,6,3]])
a = np.array([1,1,1])
obj = lambda x: np.dot(np.dot(c,x.T),x)
cons = {'type':'ineq','fun':lambda x:b-a@x.T*x}
res = minimize(obj,np.ones(3),constraints=cons,bounds=None)
print(res)

     fun: -32506953535.445816
     jac: array([-509952., -465408.,  330240.])
 message: 'Inequality constraints incompatible'
    nfev: 40
     nit: 7
    njev: 7
  status: 4
 success: False
       x: array([ 51527.84435155,  25371.16921765, -81580.46014174])
