In [2]:
import numpy as np
a = np.loadtxt('xiti1.txt')
R = a.copy()
for j in [0,2,3,5]:
    R[:,j] = R[:,j]/max(R[:,j])
for j in [1,4]:
    R[:,j] = min(R[:,j])/R[:,3]
np.savetxt('xiti1_1.txt',R)

In [3]:
import numpy as np
from scipy.stats import rankdata
a = np.loadtxt('xiti1_1.txt')
cplus = a.max(axis=0)
cminus = a.min(axis=0)
print('正理想解=',cplus,'负理想解=',cminus)
d1 = np.linalg.norm(a-cplus,axis=1)
d2 = np.linalg.norm(a-cminus,axis=1)
print(d1,d2)
f1 = d2/(d1+d2)
print('TOPSIS的评价值为：',f1)

t = cplus-a
mmin = t.min()
mmax = t.max()
rho = 0.5
xs = (mmin+rho*mmax)/(t+rho*mmax)
f2 = xs.mean(axis = 1)
print('\n关联系数=',xs,'\n关联度=',f2)

[n,m] = a.shape
cs = a.sum(axis=0)
p = a/cs
e = -(p*np.log(p)).sum(axis=0)/np.log(n)
g = 1-e
w = g/sum(g)
F = p@w
print('\nP={}\n,e={}\n,g={}\n,w={}\nF={}'.format(p,e,g,w,F))

R = [rankdata(a[:,i]) for i in np.arange(6)]
R = np.array(R).T
print('\n秩矩阵为：\n',R)
RSR = R.mean(axis=1)/n
print('RSR=',RSR)

正理想解= [  1.         280.67368421   1.           1.          87.53684211
   1.        ] 负理想解= [  0.55555556 202.           0.82352941   0.71969697  63.
   0.36111111]
[82.41176402 32.97408741  0.68560348 79.15969567] [ 0.65370882 49.44336418 82.41162215  3.27052639]
TOPSIS的评价值为： [0.0078698  0.59991377 0.99174938 0.0396763 ]

关联系数= [[1.         0.33333333 0.9955339  1.         0.61585366 0.99368477]
 [0.99562539 0.55549319 0.99652291 0.9952084  0.80027659 1.        ]
 [0.9934524  1.         1.         0.9929247  1.         0.98573046]
 [0.9888278  0.34234875 0.99983387 0.99961497 0.62534272 0.98401808]] 
关联度= [0.82306761 0.89052108 0.99535126 0.82333103]

P=[[0.3201581  0.21558679 0.22380107 0.28448276 0.21558679 0.29508197]
 [0.26482213 0.26595753 0.23445826 0.23060345 0.26595753 0.39344262]
 [0.23715415 0.29955217 0.27175844 0.20474138 0.29955217 0.16939891]
 [0.17786561 0.21890351 0.26998224 0.28017241 0.21890351 0.1420765 ]]
,e=[0.98457455 0.99306145 0.99739199 0.99338587 0.99306145 

In [11]:
import numpy as np
a = np.loadtxt('xiti2.txt')
R = a.copy()
for i in range(4):
    R[:,i] = R[:,i]/max(R[:,i])
np.savetxt('xiti2_1.txt',R)

In [12]:
import numpy as np
from scipy.stats import rankdata
a = np.loadtxt('xiti2_1.txt')
cplus = a.max(axis=0)
cminus = a.min(axis=0)
print('正理想解=',cplus,'负理想解=',cminus)
d1 = np.linalg.norm(a-cplus,axis=1)
d2 = np.linalg.norm(a-cminus,axis=1)
print(d1,d2)
f1 = d2/(d1+d2)
print('TOPSIS的评价值为：',f1)

t = cplus-a
mmin = t.min()
mmax = t.max()
rho = 0.5
xs = (mmin+rho*mmax)/(t+rho*mmax)
f2 = xs.mean(axis = 1)
print('\n关联系数=',xs,'\n关联度=',f2)

[n,m] = a.shape
cs = a.sum(axis=0)
p = a/cs
e = -(p*np.log(p)).sum(axis=0)/np.log(n)
g = 1-e
w = g/sum(g)
F = p@w
print('\nP={}\n,e={}\n,g={}\n,w={}\nF={}'.format(p,e,g,w,F))

R = [rankdata(a[:,i]) for i in np.arange(4)]
R = np.array(R).T
print('\n秩矩阵为：\n',R)
RSR = R.mean(axis=1)/n
print('RSR=',RSR)

正理想解= [1. 1. 1. 1.] 负理想解= [0.52328244 0.08939497 0.06746032 0.48262548]
[1.1006788  1.19140356 1.38272352 1.08176173 1.12749769 1.33477837
 1.15770301 1.39771341 0.51944114 0.48678814 0.4051461  1.11457227
 0.95410317 0.84003041 1.05539471 0.94246783 0.51525101 1.14535385
 0.8644493  1.14836811] [0.3879081  0.30638895 0.12368149 0.40883249 0.37540531 0.16295618
 0.34001249 0.12194844 1.07004842 1.03843275 1.14668385 0.38198688
 0.56472034 0.64900426 0.45868482 0.61515175 1.32200706 0.35040575
 0.73513967 0.47786136]
TOPSIS的评价值为： [0.26058814 0.20456034 0.08210374 0.27427484 0.24978679 0.10880177
 0.22702074 0.08024709 0.67320254 0.68084089 0.73892365 0.25524342
 0.37181433 0.43585571 0.30294632 0.39493067 0.71955436 0.23426609
 0.45958036 0.2938462 ]

关联系数= [[0.54766081 0.42146376 0.39101498 0.5675958 ]
 [0.50634723 0.40708047 0.3808752  0.52559995]
 [0.51662566 0.36907514 0.34008683 0.47402279]
 [0.53825011 0.42393854 0.39898132 0.57847116]
 [0.51793988 0.42670786 0.39898132 0.51222386